//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.08 at 01:29:15 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ns.soacookbook.com/russiandoll")
package com.soacookbook.ns.russiandoll;
