//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.24 at 10:57:13 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ns.soacookbook.com/salami", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.soacookbook.ns.salami;
