//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.04 at 06:22:34 PM EEST 
//


package org.example.suite;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for suite.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="suite">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SPADES"/>
 *     &lt;enumeration value="HEARTS"/>
 *     &lt;enumeration value="DIAMONDS"/>
 *     &lt;enumeration value="CLUBS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "suite", namespace = "http://www.example.org/Suite")
@XmlEnum
public enum Suite {

    SPADES,
    HEARTS,
    DIAMONDS,
    CLUBS;

    public String value() {
        return name();
    }

    public static Suite fromValue(String v) {
        return valueOf(v);
    }

}
